# Generated by Django 3.0 on 2019-12-12 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dribble', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='response',
            name='like',
        ),
        migrations.AddField(
            model_name='post',
            name='like',
            field=models.IntegerField(default=0),
        ),
    ]
